### ISSUE TITLE
add editor and compiler for git and terminal demos?

### ISSUE THREAD

**Issue by gaelforget** [PraCTES/MIT-PraCTES#6]
The code snippet (abbreviated) + error message below first led me to believe that adding `vim` (or `nano`) to the cloud instance environment would be needed to enable to use `git commit`. 

```
git clone https://github.com/gaelforget/MIT-PraCTES
cd MIT-PraCTES
...
git config --global core.editor vim
git commit demos/README.md 
hint: Waiting for your editor to close the file... error: unable to start editor 'vim'
Please supply the message using either -m or -F option.
```

Found [this relevant post](https://stackoverflow.com/questions/26930924/git-commit-unable-to-open-vim) and tried `sudo apt-get install nano` as suggested [here](https://www.xsofthost.com/help/how-to-install-and-use-nano-text-editor-commands-in-linux/)
but get `bash: sudo: command not found`. 

**update 1** I went back and the following works even without `vim` or `nano`

`git commit demos/README.md -m "my message`

**update 2** https://github.com/binder-examples/apt_install works to install `nano` (see below)

**Comment by gaelforget** [comment]
Will try this next : https://github.com/binder-examples/apt_install

**Comment by gaelforget** [comment]
> Will try this next : https://github.com/binder-examples/apt_install

This worked for `nano` (https://mybinder.org/v2/gh/gaelforget/apt_install/nano-test1?urlpath=lab) but the build seems to have timed out for `vim`. 

This worked also for `gfortran` and thus `MITgcm`:

![Screen Shot 2020-01-16 at 11 22 01 AM](https://user-images.githubusercontent.com/20276764/72542751-abdbbd80-3852-11ea-84d9-91d3e34d17da.png)

**Comment by hdrake** [comment]
Will schedule the announcement email for 7:45am tomorrow. Looking at your
edits now and will merge sometime tonight.

Henri Drake (he/him)
PhD Candidate
MIT/WHOI Joint Program
hdrake.github.io
